/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 model2.glb -T 
Files: model2.glb [311.97MB] > C:\Users\ASUS\Desktop\threejs\appleclone\public\models\model2-transformed.glb [23.7MB] (92%)
*/

import React from "react";
import { useGLTF, useAnimations } from "@react-three/drei";

export default function Model2(props) {
  const group = React.useRef();
  const { nodes, materials, animations } = useGLTF(
    "/models/model2-transformed.glb"
  );
  const { actions } = useAnimations(animations, group);
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Scene">
        <group name="root001">
          <mesh
            name="tripo_node_c8171499-98e4-4746-acc4-70b72f7bbd0e"
            geometry={
              nodes["tripo_node_c8171499-98e4-4746-acc4-70b72f7bbd0e"].geometry
            }
            material={
              materials["tripo_material_c8171499-98e4-4746-acc4-70b72f7bbd0e"]
            }
            position={[0.982, 0.145, 0.914]}
            rotation={[0, -0.697, 0]}
            scale={0.215}
          />
          <mesh
            name="tripo_node_c8171499-98e4-4746-acc4-70b72f7bbd0e001"
            geometry={
              nodes["tripo_node_c8171499-98e4-4746-acc4-70b72f7bbd0e001"]
                .geometry
            }
            material={
              materials["tripo_material_c8171499-98e4-4746-acc4-70b72f7bbd0e"]
            }
            position={[0.675, 0.145, 0.476]}
            rotation={[0, 1.036, 0]}
            scale={0.215}
          />
          <mesh
            name="tripo_node_c8171499-98e4-4746-acc4-70b72f7bbd0e002"
            geometry={
              nodes["tripo_node_c8171499-98e4-4746-acc4-70b72f7bbd0e002"]
                .geometry
            }
            material={
              materials["tripo_material_c8171499-98e4-4746-acc4-70b72f7bbd0e"]
            }
            position={[-0.08, 0.145, 1.768]}
            rotation={[0, 0.067, 0]}
            scale={0.215}
          />
        </group>
        <group name="root003">
          <mesh
            name="tripo_node_e4c08c00-2260-4221-901d-c2b8a07d4a90"
            geometry={
              nodes["tripo_node_e4c08c00-2260-4221-901d-c2b8a07d4a90"].geometry
            }
            material={materials.PaletteMaterial001}
            position={[-1.452, 0.207, -1.843]}
            rotation={[-Math.PI, 1.568, -Math.PI]}
            scale={0.426}
          />
          <mesh
            name="tripo_node_e4c08c00-2260-4221-901d-c2b8a07d4a90002"
            geometry={
              nodes["tripo_node_e4c08c00-2260-4221-901d-c2b8a07d4a90002"]
                .geometry
            }
            material={materials.PaletteMaterial001}
            position={[1.366, 0.198, 1.851]}
            rotation={[Math.PI, -0.034, Math.PI]}
            scale={0.426}
          />
        </group>
        <group name="Couch_54" position={[1.321, 0, -0.358]} scale={0.098}>
          <mesh
            name="Object_202"
            geometry={nodes.Object_202.geometry}
            material={materials.PaletteMaterial001}
            position={[-28.87, 3.067, -15.138]}
            rotation={[-Math.PI, 0.076, -Math.PI]}
            scale={1.244}
          />
        </group>
        <group name="StudyTable_19" position={[0.346, 0, -0.35]} scale={0.098}>
          <mesh
            name="Object_74001"
            geometry={nodes.Object_74001.geometry}
            material={materials["Plastic.001_17"]}
            position={[10.475, 2.695, 22.903]}
            rotation={[-2.242, -0.029, -3.14]}
            scale={1.276}
          />
        </group>
        <group
          name="NUVEM1"
          position={[-3.25, 0.656, 0.69]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        >
          <mesh
            name="Object_66"
            geometry={nodes.Object_66.geometry}
            material={materials.PaletteMaterial001}
            position={[-244.177, -198.682, -548.489]}
            rotation={[0, 0, 0.208]}
            scale={1.672}
          />
        </group>
        <group
          name="NUVEM_0201"
          position={[-3.25, 0.656, 0.69]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        >
          <mesh
            name="Object_69"
            geometry={nodes.Object_69.geometry}
            material={materials.PaletteMaterial001}
            position={[1577.597, -1182.003, -571.468]}
            scale={1.672}
          />
        </group>
        <group
          name="NUVEM_2_1"
          position={[-3.25, 0.656, 0.69]}
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.001}
        >
          <mesh
            name="Object_76001"
            geometry={nodes.Object_76001.geometry}
            material={materials.PaletteMaterial001}
            position={[1004.264, -2902.724, -714.62]}
            scale={1.672}
          />
        </group>
        <mesh
          name="Plane"
          geometry={nodes.Plane.geometry}
          material={materials.PaletteMaterial001}
          scale={[1, 1, 1.381]}
        />
        <mesh
          name="tripo_node_77effc33-3eee-4a23-ae83-28be088369ad"
          geometry={
            nodes["tripo_node_77effc33-3eee-4a23-ae83-28be088369ad"].geometry
          }
          material={
            materials["tripo_material_77effc33-3eee-4a23-ae83-28be088369ad"]
          }
          position={[-0.468, 0.241, 0.667]}
        />
        <mesh
          name="tripo_node_9f5b0db9-fbb8-4984-a2d5-c3af1017f2d3"
          geometry={
            nodes["tripo_node_9f5b0db9-fbb8-4984-a2d5-c3af1017f2d3"].geometry
          }
          material={
            materials["tripo_material_9f5b0db9-fbb8-4984-a2d5-c3af1017f2d3"]
          }
          position={[-0.355, 0.337, -0.862]}
        />
        <mesh
          name="Object_315"
          geometry={nodes.Object_315.geometry}
          material={materials["Plastic.001_31"]}
          position={[-0.042, 0.034, -0.822]}
          rotation={[0, 0.762, 0]}
          scale={0.098}
        />
        <mesh
          name="Object_316"
          geometry={nodes.Object_316.geometry}
          material={materials["Plastic.001_26"]}
          position={[-0.145, 0, -0.543]}
          rotation={[Math.PI, 1.545, -Math.PI]}
          scale={0.098}
        />
        <mesh
          name="Object_317"
          geometry={nodes.Object_317.geometry}
          material={materials.PaletteMaterial002}
          position={[-0.145, 0, -0.543]}
          rotation={[Math.PI, 1.545, -Math.PI]}
          scale={0.098}
        />
        <mesh
          name="Object_35"
          geometry={nodes.Object_35.geometry}
          material={materials["Plastic.001_8"]}
          position={[0.12, 0, -0.344]}
          scale={0.098}
        />
        <mesh
          name="Object_37"
          geometry={nodes.Object_37.geometry}
          material={materials["Metal.003_0"]}
          position={[0.117, 0, 0.213]}
          scale={0.098}
        />
        <mesh
          name="Object_39"
          geometry={nodes.Object_39.geometry}
          material={materials.PaletteMaterial003}
          position={[0.137, 0, 0.213]}
          scale={0.098}
        />
        <mesh
          name="Object_45"
          geometry={nodes.Object_45.geometry}
          material={materials["Plastic.001_9"]}
          position={[-0.049, 0.031, -0.664]}
          rotation={[0, 1.564, 0]}
          scale={0.098}
        />
        <mesh
          name="Object_139"
          geometry={nodes.Object_139.geometry}
          material={materials["Plastic.001_22"]}
          position={[0.033, 0, 0.135]}
          scale={0.098}
        />
        <mesh
          name="Object_140"
          geometry={nodes.Object_140.geometry}
          material={materials["Metal.003_1"]}
          position={[0.033, 0, 0.135]}
          scale={0.098}
        />
        <mesh
          name="Object_306"
          geometry={nodes.Object_306.geometry}
          material={materials.PaletteMaterial004}
          position={[0.732, 0, 0.191]}
          scale={0.098}
        />
        <mesh
          name="Object_156"
          geometry={nodes.Object_156.geometry}
          material={materials["Plastic.001_17"]}
          position={[-0.06, 0.036, -1.073]}
          scale={0.149}
        />
        <mesh
          name="Object_197"
          geometry={nodes.Object_197.geometry}
          material={materials.PaletteMaterial005}
          position={[0.269, 0, 0.002]}
          scale={0.098}
        />
        <mesh
          name="Object_125"
          geometry={nodes.Object_125.geometry}
          material={materials.lampbody}
          position={[0.183, 0, 0.251]}
          rotation={[Math.PI, 0, -Math.PI]}
          scale={0.098}
        />
        <mesh
          name="Object_127"
          geometry={nodes.Object_127.geometry}
          material={materials.papercover}
          position={[0.183, 0, 0.251]}
          rotation={[Math.PI, 0, -Math.PI]}
          scale={0.098}
        />
        <mesh
          name="Object_192"
          geometry={nodes.Object_192.geometry}
          material={materials["Plastic.001_24"]}
          position={[-0.072, 0.042, -0.429]}
          rotation={[Math.PI, 0.903, Math.PI]}
          scale={0.215}
        />
        <mesh
          name="tripo_node_940b8ad4-cab6-4803-9aeb-d0b2e6a73d4c"
          geometry={
            nodes["tripo_node_940b8ad4-cab6-4803-9aeb-d0b2e6a73d4c"].geometry
          }
          material={
            materials["tripo_material_940b8ad4-cab6-4803-9aeb-d0b2e6a73d4c"]
          }
          position={[0.747, 0.247, -0.414]}
          rotation={[0, -1.557, 0]}
          scale={0.435}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/model2-transformed.glb");
