/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 ./public/models/iphone.glb 
Author: Apple User (https://sketchfab.com/apple-user)
License: SKETCHFAB Standard (https://sketchfab.com/licenses)
Source: https://sketchfab.com/3d-models/apple-iphone-17-pro-max-43570bd2d48f48b6aafb8adbb04e346d
Title: Apple iPhone 17 Pro Max
*/

import React from 'react'
// import { useGLTF } from '@react-three/drei'
import { useGLTF, useTexture } from '@react-three/drei' // Added useTexture
import * as THREE from 'three' // Added THREE
export function Model(props) {
  const { nodes, materials } = useGLTF('/models/iphone.glb')
  const texture = useTexture('/texture.png') // Make sure this matches your file name
  texture.flipY = false // Corrects the image orientation
  texture.colorSpace = THREE.SRGBColorSpace
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_5.geometry} material={materials.jKYrqbVsPDbEaqj} position={[-0.025, 0.044, -0.015]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_7.geometry} material={materials.YVjGRIfwSbFphGH} position={[0.007, 0.07, -0.005]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_9.geometry} material={materials.iAKEWdNafBldSCV} position={[0.039, -0.033, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_11.geometry} material={materials.LqxrKBoiOXSOFqs} position={[0, -0.004, -0.005]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.uFgsppDNoPNkBqW} position={[0.007, 0.054, -0.017]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_15.geometry} material={materials.vUNWrAqjHCArnzh} position={[0.025, 0.064, -0.015]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_17.geometry} material={materials.nwfiSfJrPZRLBAj} position={[0, -0.08, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_19.geometry} material={materials.uFgsppDNoPNkBqW} position={[-0.025, 0.044, -0.014]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_21.geometry} material={materials.SLmJkLdkhbbuEfG} position={[0.025, 0.045, -0.017]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_23.geometry} material={materials.EOPlztmjOhyFwUF} position={[0.007, 0.07, -0.005]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_25.geometry} material={materials.ybSvSfarxzoBKlb} position={[-0.025, 0.054, -0.014]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_27.geometry} material={materials.vUNWrAqjHCArnzh} position={[0.007, 0.07, -0.005]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_29.geometry} material={materials.EiHyBykxPjKZBgf} position={[-0.025, 0.064, -0.015]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_31.geometry} material={materials.SLmJkLdkhbbuEfG} position={[0.025, 0.064, -0.017]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_33.geometry} material={materials.vUNWrAqjHCArnzh} position={[0.025, 0.045, -0.014]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_35.geometry} material={materials.uFgsppDNoPNkBqW} position={[0.007, 0.07, -0.005]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_37.geometry} material={materials.SMUhrjUPCjJkPUK} position={[0, -0.026, -0.013]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_39.geometry} material={materials.LqxrKBoiOXSOFqs} position={[0.015, 0.07, -0.005]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_41.geometry} material={materials.vUNWrAqjHCArnzh} position={[0.025, 0.045, -0.016]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_43.geometry} material={materials.uFgsppDNoPNkBqW} position={[0.025, 0.045, -0.014]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_45.geometry} material={materials.uFgsppDNoPNkBqW} position={[0, -0.08, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_47.geometry} material={materials.uFgsppDNoPNkBqW} position={[0.025, 0.064, -0.014]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_49.geometry} material={materials.BsXHDwLKqtDOfrW} position={[0, 0.002, -0.005]} rotation={[Math.PI, 0, 0]} scale={0.01} >
        <meshBasicMaterial  map={texture} toneMapped={false}/> 
      </mesh>
      <mesh geometry={nodes.Object_51.geometry} material={materials.uFgsppDNoPNkBqW} position={[-0.025, 0.054, -0.014]} rotation={[Math.PI, 0, 0]} scale={0.01} /> 
      <mesh geometry={nodes.Object_53.geometry} material={materials.uFgsppDNoPNkBqW} position={[0.025, 0.064, -0.017]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_55.geometry} material={materials.SLmJkLdkhbbuEfG} position={[0, -0.001, -0.01]} rotation={[Math.PI, 0, 0]} scale={0.01} />
       <mesh geometry={nodes.Object_57.geometry} material={materials.hiWLrxfkqoGxruc} position={[0, -0.085, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_59.geometry} material={materials.nwfiSfJrPZRLBAj} position={[0, -0.079, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_61.geometry} material={materials.NUlImpGytyodpBy} position={[0.025, 0.064, -0.015]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_63.geometry} material={materials.ieDmCkHnOnSIOcm} position={[-0.001, 0.07, -0.005]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_65.geometry} material={materials.edDerJJLuuabITp} position={[0, -0.08, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_67.geometry} material={materials.edDerJJLuuabITp} position={[0, -0.079, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_69.geometry} material={materials.UiBplfShRNPzcmF} position={[-0.025, 0.064, -0.015]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_71.geometry} material={materials.uFgsppDNoPNkBqW} position={[0.025, 0.048, -0.017]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_73.geometry} material={materials.CVcxUAKakDuRdCf} position={[0.007, 0.07, -0.005]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_75.geometry} material={materials.JKTmNomFyvfvVAj} position={[0.007, 0.054, -0.017]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_77.geometry} material={materials.AYSuIKiLIvlGvvQ} position={[0.025, 0.064, -0.016]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_79.geometry} material={materials.sJxAokqqlZYuwzy} position={[0, 0.045, -0.013]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_81.geometry} material={materials.ooxVuxObmmqIeuh} position={[0.039, -0.033, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_83.geometry} material={materials.SLmJkLdkhbbuEfG} position={[-0.039, 0.044, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_85.geometry} material={materials.nypJRzXNHbmJCqR} position={[0.025, 0.064, -0.017]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_87.geometry} material={materials.vUNWrAqjHCArnzh} position={[0.025, 0.064, -0.016]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_89.geometry} material={materials.vUNWrAqjHCArnzh} position={[0.007, 0.054, -0.016]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_91.geometry} material={materials.SLmJkLdkhbbuEfG} position={[0.039, 0.023, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_93.geometry} material={materials.VXTclbUnoLmmPoD} position={[0, -0.084, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_95.geometry} material={materials.AYSuIKiLIvlGvvQ} position={[0.025, 0.045, -0.016]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_97.geometry} material={materials.nypJRzXNHbmJCqR} position={[0.007, 0.054, -0.018]} rotation={[Math.PI, 0, 0]} scale={0.01} /> 
      <mesh geometry={nodes.Object_99.geometry} material={materials.NUlImpGytyodpBy} position={[0.007, 0.054, -0.016]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_101.geometry} material={materials.JKTmNomFyvfvVAj} position={[0.025, 0.064, -0.017]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_103.geometry} material={materials.uFgsppDNoPNkBqW} position={[0.025, 0.064, -0.016]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_105.geometry} material={materials.uFgsppDNoPNkBqW} position={[0.007, 0.054, -0.014]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_107.geometry} material={materials.uFgsppDNoPNkBqW} position={[0.003, 0.009, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_109.geometry} material={materials.vUNWrAqjHCArnzh} position={[0.025, 0.064, -0.016]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_111.geometry} material={materials.YQFhPSFSryEqJMp} position={[0, -0.084, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_113.geometry} material={materials.vUNWrAqjHCArnzh} position={[0.025, 0.045, -0.014]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_115.geometry} material={materials.sJxAokqqlZYuwzy} position={[0, 0.078, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_117.geometry} material={materials.nwfiSfJrPZRLBAj} position={[0, -0.082, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_119.geometry} material={materials.YQFhPSFSryEqJMp} position={[0, -0.085, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_121.geometry} material={materials.AYSuIKiLIvlGvvQ} position={[0.007, 0.054, -0.016]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_123.geometry} material={materials.hqDUrVMlYhzYusu} position={[-0.025, 0.064, -0.016]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_125.geometry} material={materials.JKTmNomFyvfvVAj} position={[0.025, 0.045, -0.017]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_127.geometry} material={materials.nypJRzXNHbmJCqR} position={[0.025, 0.045, -0.017]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_129.geometry} material={materials.uFgsppDNoPNkBqW} position={[0.007, 0.054, -0.016]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      {/* <mesh geometry={nodes.Object_131.geometry} material={materials.uFgsppDNoPNkBqW} position={[0, 0.002, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} /> */}
      <mesh geometry={nodes.Object_133.geometry} material={materials.yPEFElLJTRhfWfw} position={[0, -0.024, -0.013]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_135.geometry} material={materials.YQFhPSFSryEqJMp} position={[0, -0.085, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_137.geometry} material={materials.SLmJkLdkhbbuEfG} position={[0.007, 0.054, -0.017]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_139.geometry} material={materials.QEOvfSZiwySWiUk} position={[-0.025, 0.064, -0.015]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_141.geometry} material={materials.PJgHvfOhNXkxvzq} position={[0.039, -0.033, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_143.geometry} material={materials.SMUhrjUPCjJkPUK} position={[0, -0.026, -0.013]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_145.geometry} material={materials.awYxKfiOpRgQIxD} position={[0, -0.025, -0.013]} rotation={[Math.PI, 0, 0]} scale={0.01} />
       <mesh geometry={nodes.Object_147.geometry} material={materials.SLmJkLdkhbbuEfG} position={[-0.039, 0.016, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
       <mesh geometry={nodes.Object_149.geometry} material={materials.edDerJJLuuabITp} position={[0, -0.081, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
       <mesh geometry={nodes.Object_151.geometry} material={materials.vUNWrAqjHCArnzh} position={[0.007, 0.07, -0.005]} rotation={[Math.PI, 0, 0]} scale={0.01} />
       <mesh geometry={nodes.Object_153.geometry} material={materials.hiWLrxfkqoGxruc} position={[0, -0.085, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
       <mesh geometry={nodes.Object_155.geometry} material={materials.vUNWrAqjHCArnzh} position={[0.007, 0.054, -0.016]} rotation={[Math.PI, 0, 0]} scale={0.01} />
       <mesh geometry={nodes.Object_157.geometry} material={materials.HETovHCBsEjcSiP} position={[0, -0.084, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
       <mesh geometry={nodes.Object_159.geometry} material={materials.AYSuIKiLIvlGvvQ} position={[0.025, 0.064, -0.016]} rotation={[Math.PI, 0, 0]} scale={0.01} />
       <mesh geometry={nodes.Object_161.geometry} material={materials.NUlImpGytyodpBy} position={[0.025, 0.045, -0.014]} rotation={[Math.PI, 0, 0]} scale={0.01} />
       <mesh geometry={nodes.Object_163.geometry} material={materials.SLmJkLdkhbbuEfG} position={[-0.039, 0.03, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
       <mesh geometry={nodes.Object_165.geometry} material={materials.nwfiSfJrPZRLBAj} position={[0, -0.081, -0.009]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_167.geometry} material={materials.AYSuIKiLIvlGvvQ} position={[0.025, 0.045, -0.014]} rotation={[Math.PI, 0, 0]} scale={0.01} />
      <mesh geometry={nodes.Object_169.geometry} material={materials.uFgsppDNoPNkBqW} position={[0.025, 0.045, -0.015]} rotation={[Math.PI, 0, 0]} scale={0.01} />
    </group>
  )
}

useGLTF.preload('/models/iphone.glb')
