// src/components/Mesh.jsx
/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/mesh.glb 
*/

import React from "react";
import { useGraph } from "@react-three/fiber";
import { useGLTF, Outlines } from "@react-three/drei";
import { SkeletonUtils } from "three-stdlib";
// import { motion } from 'framer-motion-3d'

export function Model({ selectedName, onObjectClick, ...props }) {
  const { scene } = useGLTF("/models/mesh.glb");
  const clone = React.useMemo(() => SkeletonUtils.clone(scene), [scene]);
  const { nodes, materials } = useGraph(clone);

  return (
    <group {...props} dispose={null}>
      {/* --- OBJECT 1: The iPhone --- */}
      {/* Reverted back to standard <group> */}
      <group
        position={[-1.981, 1.673, 2.055]}
        rotation={[-2.762, 0.801, 2.877]}
        // Keep the "Pop" effect on click
        scale={selectedName === "iphone" ? 0.23 : 0.211}
        onClick={(e) => {
          e.stopPropagation();
          onObjectClick(e, "iphone");
        }}
      >
        <mesh
          geometry={nodes.Object_46.geometry}
          material={materials.cecc91181f1dafcc19fa}
        >
          {selectedName === "iphone" && (
            <Outlines thickness={0.05} color="hotpink" />
          )}
        </mesh>
        <mesh
          geometry={nodes.Object_29.geometry}
          material={materials["3b9594ccffa1d862f699"]}
        >
          {selectedName === "iphone" && (
            <Outlines thickness={0.05} color="hotpink" />
          )}
        </mesh>

        {/* ... (Keep all other meshes here exactly as they were) ... */}
        <mesh
          geometry={nodes.Object_52.geometry}
          material={materials["25fa7b29639901e1f310"]}
        />
        <mesh
          geometry={nodes.Object_42.geometry}
          material={materials["483cd8d2505fcf4cc33c"]}
        />
        <mesh
          geometry={nodes.Object_25.geometry}
          material={materials.e73cdd81f0248824c66f}
        />
        <mesh
          geometry={nodes.Object_48.geometry}
          material={materials["2df164b7997e629e4d7e"]}
        />
        <mesh
          geometry={nodes.Object_44.geometry}
          material={materials["13fa87e9b9ea638526bb"]}
        />
        <mesh
          geometry={nodes.Object_33.geometry}
          material={materials["8293fe999d10eb51dc07"]}
        />
        <mesh
          geometry={nodes.Object_57.geometry}
          material={materials["82823ff934002f16e6e0"]}
          position={[0, 0, 0.037]}
        />
        <mesh
          geometry={nodes.Object_59.geometry}
          material={materials.b4ad12de1fcbdd61166e}
        />
        <mesh
          geometry={nodes.Object_27.geometry}
          material={materials["5d66e4713803a9e0ad46"]}
        />
        <mesh
          geometry={nodes.Object_54.geometry}
          material={materials["299a045923a299d97c82"]}
        />
        <mesh
          geometry={nodes.Object_40.geometry}
          material={materials.cf3bfd3f874c6277f037}
        />
        <mesh
          geometry={nodes.Object_38.geometry}
          material={materials.e7fedd2cefc789ae4070}
        />
        <mesh
          geometry={nodes.Object_36.geometry}
          material={materials.b23162de4d8409eb15f1}
        />
        <mesh
          geometry={nodes.Object_23.geometry}
          material={materials.dee5a626f928a5fa4c28}
        />
        <mesh
          geometry={nodes.Object_31.geometry}
          material={materials["3a020e0705c66463c666"]}
        />
        <mesh
          geometry={nodes.Object_100.geometry}
          material={materials.a86dab30a71ca989ac8c}
        />
        <mesh
          geometry={nodes.Object_16.geometry}
          material={materials["5155c9eac3acd76d34a9"]}
        />
        <mesh
          geometry={nodes.Object_12.geometry}
          material={materials.d79c406d92ac2ea2b462}
        />
        <mesh
          geometry={nodes.Object_14.geometry}
          material={materials["8ed052ed6d3cd71ab5e3"]}
        />
        <mesh
          geometry={nodes.Object_20.geometry}
          material={materials.a18b462c494e4fd29b4b}
        />
        <mesh
          geometry={nodes.Object_18.geometry}
          material={materials["Material.006"]}
        />
        <mesh
          geometry={nodes.Object_90.geometry}
          material={materials["994433e619f1f1513042"]}
        />
        <mesh
          geometry={nodes.Object_82.geometry}
          material={materials["091912dc178e0b223122"]}
        />
        <mesh
          geometry={nodes.Object_80.geometry}
          material={materials.b8c5608ba04260006bf0}
        />
        <mesh
          geometry={nodes.Object_84.geometry}
          material={materials["6a2b4bcac74a0306e361"]}
        />
        <mesh
          geometry={nodes.Object_88.geometry}
          material={materials["50c2259ef1b62ea11389"]}
        />
        <mesh
          geometry={nodes.Object_70.geometry}
          material={materials.c306087c056eb775dddc}
        />
        <mesh
          geometry={nodes.Object_74.geometry}
          material={materials["4e2775e8ab652e8ec892"]}
        />
        <mesh
          geometry={nodes.Object_72.geometry}
          material={materials["4a6c96a0e91c63810afa"]}
        />
        <mesh
          geometry={nodes.Object_65.geometry}
          material={materials.bfb52a03e58fd454437d}
        />
        <mesh
          geometry={nodes.Object_77.geometry}
          material={materials.c1f38c49c59514a1f2d9}
        />
        <mesh
          geometry={nodes.Object_62.geometry}
          material={materials.ec12d37933cc378c1226}
        />
        <mesh
          geometry={nodes.Object_86.geometry}
          material={materials.f960f58dcaeee45e59c1}
        />
        <mesh
          geometry={nodes.Object_67.geometry}
          material={materials["906edd797edf30e1b5ca"]}
        />
        <mesh
          geometry={nodes.Object_92.geometry}
          material={materials["16d76ca3cbeebab956f0"]}
        />
        <mesh
          geometry={nodes.Object_96.geometry}
          material={materials.a86dab30a71ca989ac8c}
        />
        <mesh
          geometry={nodes.Object_98.geometry}
          material={materials.a86dab30a71ca989ac8c}
        />
        <mesh
          geometry={nodes.Object_94.geometry}
          material={materials["15e105904fe114289c62"]}
        />
      </group>

      {/* --- Keep Cube, Floor, Chair unchanged below --- */}
      <mesh
        geometry={nodes.Cube.geometry}
        material={materials.Material}
        position={[-2.421, 1.202, 4.351]}
        scale={0.738}
        onClick={(e) => {
          e.stopPropagation();
          onObjectClick(e, "cube");
        }}
      >
        {selectedName === "cube" && (
          <Outlines thickness={0.1} color="hotpink" />
        )}
      </mesh>

      <mesh
        geometry={nodes.Plane.geometry}
        material={materials["Material.004"]}
        position={[1.541, 0.149, -0.529]}
        scale={5.555}
        onClick={(e) => {
          e.stopPropagation();
          onObjectClick(e, null);
        }}
      />

      <mesh
        geometry={nodes.lambert1.geometry}
        material={materials.lambert1}
        position={[-1.645, 0.198, 3.637]}
        rotation={[-Math.PI, 1.227, -Math.PI]}
        scale={0.027}
        onClick={(e) => {
          e.stopPropagation();
          onObjectClick(e, "chair");
        }}
      >
        {selectedName === "chair" && <Outlines thickness={2} color="hotpink" />}
      </mesh>

      <spotLight
        intensity={37.661}
        angle={1.004}
        penumbra={0.636}
        decay={2}
        position={[5.648, 5.745, -3.578]}
        rotation={[-2.526, 0.77, 2.548]}
        scale={0.156}
        target={nodes.Spot.target}
      >
        <primitive object={nodes.Spot.target} position={[0, 0, -1]} />
      </spotLight>
    </group>
  );
}

useGLTF.preload("/models/mesh.glb");
